#spring.application.name=currency-fetcher-service
spring:
  application:
    name: currency-fetcher-service
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
    admin:
      auto-create: true
      properties:
        replication.factor: 1

topic:
  send-currency: send-currency-event-v2

exchange-rate-api:
  key: 32cccc1183ded4da1b404084
  base-url: https://v6.exchangerate-api.com/v6
server:
  port: 8081
